### ISSUE TITLE
What about non-binary people?

### ISSUE THREAD

**Issue by patrickbucher** [fb55/boolbase#2]
Just having true and false might offend certain kinds of people, say transgenders or other non-binary people. Shouldn't we have a third function? Maybe along the lines of Java's `Boolean` which cannot just be true or false but also null.

**Comment by fb55** [comment]
I'd argue that `null` would be discriminatory as well, as it would assume these people don't have a gender.

This is a very hard problem to model with boolean logic, so for now this library will remain terrible in this regard. It is a relict from another time anyway (already more than 4 years old, which should be roughly equal to 80 human years).

**Comment by patrickbucher** [comment]
Maybe `null` was the wrong idea, but what about `undefined`? This means: there is a gender, but one that cannot be defined (yet).
